language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install nose pylint
# command to run tests
script:
  - find . -name "*.py" | grep -v chatops.py | xargs pylint -E
  
